name: "other repo"
on: push


jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - run: |
              mkdir new_repo
              cp -r ./project ./new_repo
      - run: |
              cd new_repo
              pwd
              git init
              git config --global user.name "abdelali4"
              git config --global user.email "abdelali.elhammadi@gmail.com"
              git config --global credential.helper store
              git config --global user.password "${{ secrets.ACCOUNT_TOKEN }}"
              git remote add origin https://github.com/abdelali4/keycloak.git
              git checkout -b main
              git add .
              git commit -m "ha"
              echo "haaa"
              git push -u origin main
        
      
    
